export const keywords: string[] = [
  // Brand
  "rehooks",
  "rehooks-ts",
  "rehooks-api",
  "rehooks-cli",
  "rehooks-hooks",
  "rehooks ts",
  "rehooks api",
  "rehooks cli",
  "rehooks library",
  "rehooks typescript",
  "usehooks",

  // React stuff
  "react",
  "react hooks",
  "react reusable hooks",
  "react hooks best practice",
  "react hooks library",
  "react-hooks",
  "react-hooks library",
  "react typescript hooks",
  "react typescript library",
  "react hooks library",
  "react ecosystem",

  // Libs & tools
  "react",
  "typescript",
  "javascript",
  "markdown",
  "markdownx",
  "mdx",
  "md",
  "next",
  "js",
  "ts",
  "lib",
  "library",
  "nextjs",
  "redis",
  "rate limit",
  "rate limiting",
  "rate limiter",
  "upstash",
  "docs",
  "documentation",
  "fumadocs",
  "nextjs 15",
  "tailwindcss",
  "api",
  "cli",
  "tailwind",
  "tsx",
  "jsx",
  "npx",
  "turbo",
  "turborepo",
  "monorepo",
  "rust",
  "rust lang",
  "rust programming language",
  "rust-lang",
  "router",
  "routing",
  "dev",

  // Other
  "pyr33x",
  "pyrex",
  "mehdi",
  "mahdi",
  "mehdi parandak",
  "mahdi parandak",
];
